# Generated by Django 3.2.4 on 2021-07-07 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
