# Generated by Django 3.2.4 on 2021-07-09 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_account_cart'),
        ('carts', '0007_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
        ),
    ]
