# Generated by Django 3.2.4 on 2021-07-09 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_account_cart'),
        ('ads', '0002_ad_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
        ),
    ]
