# Generated by Django 3.2.4 on 2021-07-09 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='cart',
        ),
    ]
