# Generated by Django 3.2.4 on 2021-07-09 06:42

import aStore.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to=aStore.utils.upload_image_path)),
                ('price', models.DecimalField(decimal_places=2, default=50, max_digits=20)),
                ('category', models.CharField(choices=[('free', 'Free'), ('shop', 'Shop')], default='shop', max_length=120)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('condition', models.CharField(choices=[('free', 'Free'), ('shop', 'Shop')], default='shop', max_length=120)),
                ('featured', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
