# Generated by Django 3.2.4 on 2021-07-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_offer_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='types',
            field=models.CharField(choices=[('free', 'Free'), ('shop', 'Shop')], default='shop', max_length=120),
        ),
        migrations.AlterField(
            model_name='offer',
            name='category',
            field=models.CharField(choices=[('maison', 'Maison')], default='shop', max_length=120),
        ),
        migrations.AlterField(
            model_name='offer',
            name='condition',
            field=models.CharField(choices=[('maison', 'Maison')], default='shop', max_length=120),
        ),
    ]
