# Generated by Django 3.2.4 on 2021-07-10 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_account_timestamp'),
        ('offers', '0004_alter_offer_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
        ),
    ]
