# Generated by Django 3.2.4 on 2021-07-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('free', 'Free'), ('shop', 'Shop')], default='free', max_length=120),
        ),
    ]
