# Generated by Django 3.2.4 on 2021-07-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('free', 'Free'), ('shop', 'Shop')], default='shop', max_length=120),
        ),
    ]
